[book]
authors = ["Stefan Hagen"]
language = "en"
multilingual = false
src = "."
title = "Locked-dict"

[preprocessor.embed]

[build]
builddir = "book"

[output.html]
mathjax-support = true
site-url = "/docs/locked-dict"
git-repository-url = "https://git.sr.ht/~sthagen/locked-dict"

